services:
    jorgelive_ical.factory:
        class: jorgelive\IcalBundle\Factory\Factory
        calls:
            - [ setTimezone, ['%jorgelive_ical.default_timezone%']]
            - [ setProdid, ['%jorgelive_ical.default_prodid%']]
